easy_admin:
    site_name: 'Studiary'
    entities:
        User:
            class: App\Entity\User
            controller: App\Controller\Admin\AdminController
            list:
                fields:
                    - 'id'
                    - 'email'
                    - 'firstName'
                    - 'lastName'
                    - 'grade'
                    - 'roles'
            form:
                fields:
                    - 'email'
                    - 'firstName'
                    - 'lastName'
                    - 'grade'
                    -   property: 'roles'
                        label: 'Role'
                        type: 'choice'
                        type_options:
                            mapped: true
                            expanded: true
                            multiple: true
                            choices: { 'Teacher': 'ROLE_TEACHER', 'Student': 'ROLE_STUDENT'  }
            new:
                fields:
                    - { property: 'plainPassword', label: 'Password', type: 'password', type_options: { required: false } }
        Lesson:
            class: App\Entity\Lesson
            form:
                fields:
                    - 'name'
                    - { property: 'startDate', type: 'date' }
                    - { property: 'endDate', type: 'date' }
                    - { property: 'startTime', type: 'time' }
                    - { property: 'endTime', type: 'time' }
                    - { property: 'teacher', type: 'entity', type_options: { class: 'App\Entity\User', multiple: false, query_builder: 'App\Repository\UserRepository::adminQueryBuilderForTeacher' }}
                    - 'subject'
                    - 'grade'
        Subject:
            class: App\Entity\Subject
            form:
                fields:
                    - 'name'
        Grade:
            class: App\Entity\Grade
            form:
                fields:
                    - 'name'
            edit:
                fields:
                    - 'students'
                    - 'lessons'