easy_admin:
    site_name: 'Studiary'
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - 'id'
                    - 'email'
                    - 'firstName'
                    - 'lastName'
                    - 'grade'
                    - 'roles'
            form:
                fields:
                    - 'email'
                    - 'firstName'
                    - 'lastName'
                    - 'grade'
            new:
                fields:
                    - 'password'
        Teacher:
            class: App\Entity\User
            list:
                dql_filter: "entity.roles LIKE '%%ROLE_TEACHER%%'"
                fields:
                    - 'id'
                    - 'email'
                    - 'firstName'
                    - 'lastName'
            form:
                fields:
                    - 'email'
                    - 'firstName'
                    - 'lastName'
            new:
                fields:
                    - 'password'
        Lesson:
            class: App\Entity\Lesson
            form:
                fields:
                    - 'name'
                    - 'startDate'
                    - 'endDate'
                    - 'startTime'
                    - 'endTime'
                    - 'teacher'
                    - 'subject'
                    - 'grade'
        Subject:
            class: App\Entity\Subject
            form:
                fields:
                    - 'name'
        Grade:
            class: App\Entity\Grade
            form:
                fields:
                    - 'name'
            edit:
                fields:
                    - 'students'
                    - 'lessons'
