easy_admin:
    site_name: 'Studiary'
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - 'id'
                    - 'email'
                    - 'firstName'
                    - 'lastName'
                    - 'grade'
                    - 'roles'
            form:
                fields:
                    - 'email'
                    - 'firstName'
                    - 'lastName'
                    - 'grade'
                    -   property: 'roles'
                        label: 'Role'
                        type: 'choice'
                        type_options:
                            mapped: true
                            expanded: true
                            multiple: true
                            choices: { 'Teacher': 'ROLE_TEACHER', 'Student': 'ROLE_STUDENT'  }
            new:
                fields:
                    - 'password'
        Lesson:
            class: App\Entity\Lesson
            form:
                fields:
                    - 'name'
                    - { property: 'startDate', type: 'date' }
                    - { property: 'endDate', type: 'date' }
                    - { property: 'startTime', type: 'time' }
                    - { property: 'endTime', type: 'time' }
                    - 'teacher'
                    - 'subject'
                    - 'grade'
        Subject:
            class: App\Entity\Subject
            form:
                fields:
                    - 'name'
        Grade:
            class: App\Entity\Grade
            form:
                fields:
                    - 'name'
            edit:
                fields:
                    - 'students'
                    - 'lessons'