easy_admin:
    site_name: 'Studiary'
    entities:
        User:
            class: App\Entity\User
        Lesson:
            class: App\Entity\Lesson
        Subject:
            class: App\Entity\Subject
            form:
                fields:
                    - 'name'
        Grade:
            class: App\Entity\Grade
            form:
                fields:
                    - 'name'
