easy_admin:
   entities:
       Grade:
           class: App\Entity\Grade
           form:  # <-- 'form' is applied to both 'new' and 'edit' views
               fields:
                   - 'name'
                   - { property: 'users', type_options: { by_reference: false } }

       User:
           class: App\Entity\User

       Subject:
           class: App\Entity\Subject

       Lesson:
           class: App\Entity\Lesson




