# Index
index:
  path: /
  controller: App\Controller\HomeController::index

# Login
login:
  path: /login
  controller: App\Controller\SecurityController::login

# Logout
logout: 
  path: /logout
  controller: App\Controller\SecurityController::logout


# Note
note_index: 
  path: /note
  controller: App\Controller\SecurityController::index