# Index
index:
    path: /
    controller: App\Controller\HomeController::index

# Login
login:
    path: /login
    controller: App\Controller\SecurityController::login

# Logout
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# Notes
notes_index:
    path: /notes/
    controller: App\Controller\NoteController::index
    methods: GET

note_new:
    path: /note/new
    controller: App\Controller\NoteController::new
    methods: GET|POST

note_show:
    path: /note/{id}
    controller: App\Controller\NoteController::show
    methods: GET

note_edit:
    path: /note/{id}/edit
    controller: App\Controller\NoteController::edit
    methods: GET|POST

note_delete:
    path: /note/{id}
    controller: App\Controller\NoteController::delete
    methods: DELETE
