# Index
index:
    path: /
    controller: App\Controller\HomeController::index

# Account
account:
    path: /account
    controller: App\Controller\AccountController::index


# Login
login:
    path: /login
    controller: App\Controller\SecurityController::login

# Logout
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# Notes
notes_index:
    path: /notes/
    controller: App\Controller\NoteController::index
    methods: GET

notes_new:
    path: /notes/new
    controller: App\Controller\NoteController::new
    methods: GET|POST

notes_show:
    path: /notes/{id}
    controller: App\Controller\NoteController::show
    methods: GET

notes_edit:
    path: /notes/{id}/edit
    controller: App\Controller\NoteController::edit
    methods: GET|POST

notes_delete:
    path: /notes/{id}
    controller: App\Controller\NoteController::delete
    methods: DELETE
